
// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Analyzes user-provided story text to identify key elements for RPG generation.
 *
 * - analyzeSourceMaterial - Function to analyze the story text.
 * - AnalyzeSourceMaterialInput - Input type for the function.
 * - AnalyzeSourceMaterialOutput - Output type for theFunction.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeSourceMaterialInputSchema = z.object({
  storyText: z
    .string()
    .describe('The text of the story to analyze. This is the source material for the RPG.'),
  // Added for model selection
  aiSettings: z.object({
    provider: z.enum(['googleAI', 'ollama']).optional().default('googleAI'),
    ollamaModel: z.string().optional(),
  }).optional(),
});
export type AnalyzeSourceMaterialInput = z.infer<typeof AnalyzeSourceMaterialInputSchema>;

const AnalyzeSourceMaterialOutputSchema = z.object({
  plotPoints: z.string().describe('Key plot points of the story.'),
  characters: z.string().describe('Important characters in the story.'),
  settings: z.string().describe('Key settings and locations in the story.'),
  themes: z.string().describe('Underlying themes explored in the story.'),
  tone: z.string().describe('Overall tone and style of the story.'),
});
export type AnalyzeSourceMaterialOutput = z.infer<typeof AnalyzeSourceMaterialOutputSchema>;

export async function analyzeSourceMaterial(input: AnalyzeSourceMaterialInput): Promise<AnalyzeSourceMaterialOutput> {
  return analyzeSourceMaterialFlow(input);
}

const analyzeSourceMaterialPromptObj = ai.definePrompt({
  name: 'analyzeSourceMaterialPrompt',
  input: {schema: AnalyzeSourceMaterialInputSchema},
  output: {schema: AnalyzeSourceMaterialOutputSchema},
  prompt: `You are a literary analyst tasked with dissecting a story to extract its core elements.

  Analyze the following story text and identify the key plot points, important characters, key settings, underlying themes, and overall tone.

  Story Text: {{{storyText}}}

  Format your response as a JSON object with the following keys:
  - plotPoints: Key plot points of the story.
  - characters: Important characters in the story.
  - settings: Key settings and locations in the story.
  - themes: Underlying themes explored in the story.
  - tone: Overall tone and style of the story.`,
});

const analyzeSourceMaterialFlow = ai.defineFlow(
  {
    name: 'analyzeSourceMaterialFlow',
    inputSchema: AnalyzeSourceMaterialInputSchema,
    outputSchema: AnalyzeSourceMaterialOutputSchema,
  },
  async (input) => {
    let modelName = 'googleai/gemini-2.0-flash'; // Default model
    if (input.aiSettings?.provider === 'ollama' && input.aiSettings?.ollamaModel) {
      modelName = `ollama/${input.aiSettings.ollamaModel}`;
    }

    const {output} = await analyzeSourceMaterialPromptObj(
        { storyText: input.storyText }, // Pass only relevant fields to prompt
        { model: modelName }
    );
    return output!;
  }
);
